return {[[16x12
................
................
q..........qqqqq
q..........q...q
q........q.q.j.q
q........aaq...q
q.b......##....q
qerrrrrrrqqqqqqq
q...............
qqqq............
q.....p.........
qqqqqqqqqqqqqqqq
]]}