return {[[16x12
..qqqqqq........
..q.............
..q.b...........
..qp............
..qqq...q.......
..q....q.q......
..q....a..q.....
..qqqqa#w#q.....
....s##.j.q.....
....##q...qkkkkk
......qqqqqqqqqq
................
]],
{
    'hold down and release z',
    'to drop the bomb',
}
}